# Feature Engineering Configuration
temporal_features:
  enable_cyclical_encoding: true
  cyclical_features:
    - Hour
    - DayOfWeek
    - Month
  
  lag_features:
    - crime_rate_last_1h
    - crime_rate_last_3h_avg
    - crime_rate_last_6h_sum
    - crime_rate_yesterday_same_hour
    - was_hourly_hotspot_last_hour
    - was_daily_hotspot_yesterday
    - was_hotspot_last_year_same_day

spatial_features:
  district_population_years:
    - 2020
    - 2021
    - 2022
    - 2023
  
crime_features:
  crime_category_mapping:
  violent_crimes:
    - ARSON
    - ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER
    - ASSAULT WITH DEADLY WEAPON
    - AGGRAVATED ASSAULT
    - ATTEMPTED ROBBERY
    - BATTERY - SIMPLE ASSAULT
    - BATTERY ON A FIREFIGHTER
    - BATTERY POLICE (SIMPLE)
    - BRANDISH WEAPON
    - CRIMINAL HOMICIDE
    - CRIMINAL THREATS - NO WEAPON DISPLAYED
    - DISCHARGE FIREARMS/SHOTS FIRED
    - DRUNK ROLL
    - EXTORTION
    - FALSE IMPRISONMENT
    - HUMAN TRAFFICKING - COMMERCIAL SEX ACTS
    - HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE
    - INTIMATE PARTNER - AGGRAVATED ASSAULT
    - INTIMATE PARTNER - SIMPLE ASSAULT
    - KIDNAPPING
    - KIDNAPPING - GRAND ATTEMPT
    - LYNCHING
    - LYNCHING - ATTEMPTED
    - MANSLAUGHTER, NEGLIGENT
    - OTHER ASSAULT
    - ROBBERY
    - SHOTS FIRED AT INHABITED DWELLING
    - SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT
    - STALKING
    - THREATENING PHONE CALLS/LETTERS
    - THROWING OBJECT AT MOVING VEHICLE
    - WEAPONS POSSESSION/BOMBING

  property_crimes:
    - BIKE - ATTEMPTED STOLEN
    - BIKE - STOLEN
    - BOAT - STOLEN
    - BURGLARY
    - BURGLARY FROM VEHICLE
    - BURGLARY FROM VEHICLE, ATTEMPTED
    - BURGLARY, ATTEMPTED
    - DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER
    - DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01
    - DISHONEST EMPLOYEE - GRAND THEFT
    - DISHONEST EMPLOYEE - PETTY THEFT
    - DISHONEST EMPLOYEE ATTEMPTED THEFT
    - DRIVING WITHOUT OWNER CONSENT (DWOC)
    - GRAND THEFT / AUTO REPAIR
    - PETTY THEFT - AUTO REPAIR
    - PICKPOCKET
    - PICKPOCKET, ATTEMPT
    - PURSE SNATCHING
    - PURSE SNATCHING - ATTEMPT
    - SHOPLIFTING - ATTEMPT
    - SHOPLIFTING - PETTY THEFT ($950 & UNDER)
    - SHOPLIFTING-GRAND THEFT ($950.01 & OVER)
    - TELEPHONE PROPERTY - DAMAGE
    - THEFT FROM MOTOR VEHICLE - ATTEMPT
    - THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)
    - THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)
    - THEFT FROM PERSON - ATTEMPT
    - THEFT PLAIN - ATTEMPT
    - THEFT PLAIN - PETTY ($950 & UNDER)
    - THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD
    - THEFT, COIN MACHINE - ATTEMPT
    - THEFT, COIN MACHINE - GRAND ($950.01 & OVER)
    - THEFT, COIN MACHINE - PETTY ($950 & UNDER)
    - THEFT, PERSON
    - TILL TAP - GRAND THEFT ($950.01 & OVER)
    - TILL TAP - PETTY ($950 & UNDER)
    - TRESPASSING
    - VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)
    - VANDALISM - MISDEAMEANOR ($399 OR UNDER)
    - VEHICLE - ATTEMPT STOLEN
    - VEHICLE - STOLEN
    - VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, BIKES, ETC)

  sex_crimes:
    - BATTERY WITH SEXUAL CONTACT
    - BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM
    - INDECENT EXPOSURE
    - LEWD CONDUCT
    - ORAL COPULATION
    - PANDERING
    - PEEPING TOM
    - PIMPING
    - RAPE, ATTEMPTED
    - RAPE, FORCIBLE
    - SEX OFFENDER REGISTRANT OUT OF COMPLIANCE
    - SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ)
    - SEXUAL PENETRATION W/FOREIGN OBJECT
    - SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH

  crimes_against_children:
    - CHILD ABANDONMENT
    - CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT
    - CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT
    - CHILD ANNOYING (17YRS & UNDER)
    - CHILD NEGLECT (SEE 300 W.I.C.)
    - CHILD PORNOGRAPHY
    - CHILD STEALING
    - CONTRIBUTING
    - CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)
    - DRUGS, TO A MINOR
    - INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)
    - LEWD/LASCIVIOUS ACTS WITH CHILD
    - LETTERS, LEWD - TELEPHONE CALLS, LEWD

  fraud_financial_crimes:
    - BUNCO, ATTEMPT
    - BUNCO, GRAND THEFT
    - BUNCO, PETTY THEFT
    - COUNTERFEIT
    - CREDIT CARDS, FRAUD USE ($950 & UNDER
    - CREDIT CARDS, FRAUD USE ($950.01 & OVER)
    - DOCUMENT FORGERY / STOLEN FELONY
    - DOCUMENT WORTHLESS ($200 & UNDER)
    - DOCUMENT WORTHLESS ($200.01 & OVER)
    - EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)
    - EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)
    - GRAND THEFT / INSURANCE FRAUD
    - THEFT OF IDENTITY
    - UNAUTHORIZED COMPUTER ACCESS

  crimes_against_public_order_safety:
    - BIGAMY
    - BLOCKING DOOR INDUCTION CENTER
    - BOMB SCARE
    - CRUELTY TO ANIMALS
    - DISRUPT SCHOOL
    - DISTURBING THE PEACE
    - FAILURE TO DISPERSE
    - FAILURE TO YIELD
    - ILLEGAL DUMPING
    - INCITING A RIOT
    - OTHER MISCELLANEOUS CRIME
    - PROWLER
    - RECKLESS DRIVING
    - REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)

  crimes_against_justice_government:
    - BRIBERY
    - CONSPIRACY
    - CONTEMPT OF COURT
    - FALSE POLICE REPORT
    - FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO)
    - FIREARMS RESTRAINING ORDER (FIREARMS RO)
    - RESISTING ARREST
    - VIOLATION OF COURT ORDER
    - VIOLATION OF RESTRAINING ORDER
    - VIOLATION OF TEMPORARY RESTRAINING ORDER
    
  severity_mapping:
    1: Serious
    2: Less Serious
    
hotspot_detection:
  z_score_threshold: 1.5
  quantile_threshold: 0.75
  rolling_window_hours: 24
  min_periods: 12
  
weather_features:
  enable: true
  features:
    - Temp
    - Wspeed
    
features_to_drop:
  - Crm Cd 1
  - Crm Cd 2
  - Crm Cd 3
  - Crm Cd 4
  - Cross Street
  
highly_correlated_features:
  - Yearly_Crime_Rate_per_1000
  - crime_rate_last_3h_avg
  - crime_rate_last_6h_sum
  - Month_cos
